/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ppratim' at '2/8/17 9:34 PM' with Gradle 2.14.1
 *
 * @author ppratim, @date 2/8/17 9:34 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
